# Generated by Django 4.2.11 on 2024-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_resume_user_id_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='user_id',
            field=models.CharField(default='-1', max_length=20),
        ),
    ]
