# Generated by Django 4.2.11 on 2024-03-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_remove_resume_user_resume_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
