# Generated by Django 4.2.11 on 2024-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='soft_skill',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='resume',
            name='technical_skill',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
